// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

#ifndef __CONFIGF_H_
#define __CONFIGF_H_

#include <map>
#include <string>
#include <vector>
#include "tup/Tars.h"
using namespace std;
#include "servant/ServantProxy.h"
#include "servant/Servant.h"
#include "promise/promise.h"


namespace tars
{
    struct ConfigInfo : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.ConfigInfo";
        }
        static string MD5()
        {
            return "fa53cbb9dfbff6a5a090cde6b1ed2089";
        }
        ConfigInfo()
        :appname(""),servername(""),filename(""),bAppOnly(false),host(""),setdivision("")
        {
        }
        void resetDefautlt()
        {
            appname = "";
            servername = "";
            filename = "";
            bAppOnly = false;
            host = "";
            setdivision = "";
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(appname, 0);
            _os.write(servername, 1);
            _os.write(filename, 2);
            _os.write(bAppOnly, 3);
            if (host != "")
            {
                _os.write(host, 4);
            }
            if (setdivision != "")
            {
                _os.write(setdivision, 5);
            }
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(appname, 0, true);
            _is.read(servername, 1, true);
            _is.read(filename, 2, true);
            _is.read(bAppOnly, 3, true);
            _is.read(host, 4, false);
            _is.read(setdivision, 5, false);
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(appname,"appname");
            _ds.display(servername,"servername");
            _ds.display(filename,"filename");
            _ds.display(bAppOnly,"bAppOnly");
            _ds.display(host,"host");
            _ds.display(setdivision,"setdivision");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(appname, true);
            _ds.displaySimple(servername, true);
            _ds.displaySimple(filename, true);
            _ds.displaySimple(bAppOnly, true);
            _ds.displaySimple(host, true);
            _ds.displaySimple(setdivision, false);
            return _os;
        }
    public:
        std::string appname;
        std::string servername;
        std::string filename;
        tars::Bool bAppOnly;
        std::string host;
        std::string setdivision;
    };
    inline bool operator==(const ConfigInfo&l, const ConfigInfo&r)
    {
        return l.appname == r.appname && l.servername == r.servername && l.filename == r.filename && l.bAppOnly == r.bAppOnly && l.host == r.host && l.setdivision == r.setdivision;
    }
    inline bool operator!=(const ConfigInfo&l, const ConfigInfo&r)
    {
        return !(l == r);
    }

    struct GetConfigListInfo : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.GetConfigListInfo";
        }
        static string MD5()
        {
            return "d3a0899b1f400183661be8f0b44568f6";
        }
        GetConfigListInfo()
        :appname(""),servername(""),bAppOnly(false),host(""),setdivision(""),containername("")
        {
        }
        void resetDefautlt()
        {
            appname = "";
            servername = "";
            bAppOnly = false;
            host = "";
            setdivision = "";
            containername = "";
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(appname, 0);
            if (servername != "")
            {
                _os.write(servername, 1);
            }
            if (bAppOnly != false)
            {
                _os.write(bAppOnly, 2);
            }
            if (host != "")
            {
                _os.write(host, 3);
            }
            if (setdivision != "")
            {
                _os.write(setdivision, 4);
            }
            if (containername != "")
            {
                _os.write(containername, 5);
            }
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(appname, 0, true);
            _is.read(servername, 1, false);
            _is.read(bAppOnly, 2, false);
            _is.read(host, 3, false);
            _is.read(setdivision, 4, false);
            _is.read(containername, 5, false);
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(appname,"appname");
            _ds.display(servername,"servername");
            _ds.display(bAppOnly,"bAppOnly");
            _ds.display(host,"host");
            _ds.display(setdivision,"setdivision");
            _ds.display(containername,"containername");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(appname, true);
            _ds.displaySimple(servername, true);
            _ds.displaySimple(bAppOnly, true);
            _ds.displaySimple(host, true);
            _ds.displaySimple(setdivision, true);
            _ds.displaySimple(containername, false);
            return _os;
        }
    public:
        std::string appname;
        std::string servername;
        tars::Bool bAppOnly;
        std::string host;
        std::string setdivision;
        std::string containername;
    };
    inline bool operator==(const GetConfigListInfo&l, const GetConfigListInfo&r)
    {
        return l.appname == r.appname && l.servername == r.servername && l.bAppOnly == r.bAppOnly && l.host == r.host && l.setdivision == r.setdivision && l.containername == r.containername;
    }
    inline bool operator!=(const GetConfigListInfo&l, const GetConfigListInfo&r)
    {
        return !(l == r);
    }


    /* callback of async proxy for client */
    class ConfigPrxCallback: public tars::ServantProxyCallback
    {
    public:
        virtual ~ConfigPrxCallback(){}
        virtual void callback_ListAllConfigByInfo(tars::Int32 ret,  const vector<std::string>& vf)
        { throw std::runtime_error("callback_ListAllConfigByInfo() override incorrect."); }
        virtual void callback_ListAllConfigByInfo_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_ListAllConfigByInfo_exception() override incorrect."); }

        virtual void callback_ListConfig(tars::Int32 ret,  const vector<std::string>& vf)
        { throw std::runtime_error("callback_ListConfig() override incorrect."); }
        virtual void callback_ListConfig_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_ListConfig_exception() override incorrect."); }

        virtual void callback_ListConfigByInfo(tars::Int32 ret,  const vector<std::string>& vf)
        { throw std::runtime_error("callback_ListConfigByInfo() override incorrect."); }
        virtual void callback_ListConfigByInfo_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_ListConfigByInfo_exception() override incorrect."); }

        virtual void callback_checkConfig(tars::Int32 ret,  const std::string& result)
        { throw std::runtime_error("callback_checkConfig() override incorrect."); }
        virtual void callback_checkConfig_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_checkConfig_exception() override incorrect."); }

        virtual void callback_checkConfigByInfo(tars::Int32 ret,  const std::string& result)
        { throw std::runtime_error("callback_checkConfigByInfo() override incorrect."); }
        virtual void callback_checkConfigByInfo_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_checkConfigByInfo_exception() override incorrect."); }

        virtual void callback_loadConfig(tars::Int32 ret,  const std::string& config)
        { throw std::runtime_error("callback_loadConfig() override incorrect."); }
        virtual void callback_loadConfig_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_loadConfig_exception() override incorrect."); }

        virtual void callback_loadConfigByHost(tars::Int32 ret,  const std::string& config)
        { throw std::runtime_error("callback_loadConfigByHost() override incorrect."); }
        virtual void callback_loadConfigByHost_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_loadConfigByHost_exception() override incorrect."); }

        virtual void callback_loadConfigByInfo(tars::Int32 ret,  const std::string& config)
        { throw std::runtime_error("callback_loadConfigByInfo() override incorrect."); }
        virtual void callback_loadConfigByInfo_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_loadConfigByInfo_exception() override incorrect."); }

    public:
        virtual const map<std::string, std::string> & getResponseContext() const
        {
            CallbackThreadData * pCbtd = CallbackThreadData::getData();
            assert(pCbtd != NULL);

            if(!pCbtd->getContextValid())
            {
                throw TC_Exception("cann't get response context");
            }
            return pCbtd->getResponseContext();
        }

    public:
        virtual int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __Config_all[]=
            {
                "ListAllConfigByInfo",
                "ListConfig",
                "ListConfigByInfo",
                "checkConfig",
                "checkConfigByInfo",
                "loadConfig",
                "loadConfigByHost",
                "loadConfigByInfo"
            };
            pair<string*, string*> r = equal_range(__Config_all, __Config_all+8, string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __Config_all)
            {
                case 0:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_ListAllConfigByInfo_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    vector<std::string> vf;
                    _is.read(vf, 2, true);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response.context);

                    callback_ListAllConfigByInfo(_ret, vf);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_ListConfig_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    vector<std::string> vf;
                    _is.read(vf, 3, true);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response.context);

                    callback_ListConfig(_ret, vf);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_ListConfigByInfo_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    vector<std::string> vf;
                    _is.read(vf, 2, true);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response.context);

                    callback_ListConfigByInfo(_ret, vf);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_checkConfig_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    std::string result;
                    _is.read(result, 4, true);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response.context);

                    callback_checkConfig(_ret, result);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 4:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_checkConfigByInfo_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    std::string result;
                    _is.read(result, 2, true);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response.context);

                    callback_checkConfigByInfo(_ret, result);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 5:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_loadConfig_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    std::string config;
                    _is.read(config, 4, true);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response.context);

                    callback_loadConfig(_ret, config);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 6:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_loadConfigByHost_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    std::string config;
                    _is.read(config, 4, true);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response.context);

                    callback_loadConfigByHost(_ret, config);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 7:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_loadConfigByInfo_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    std::string config;
                    _is.read(config, 2, true);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response.context);

                    callback_loadConfigByInfo(_ret, config);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<ConfigPrxCallback> ConfigPrxCallbackPtr;

    /* callback of promise async proxy for client */
    class ConfigPrxCallbackPromise: public tars::ServantProxyCallback
    {
    public:
        virtual ~ConfigPrxCallbackPromise(){}
    public:
        struct PromiseListAllConfigByInfo: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            vector<std::string> vf;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< ConfigPrxCallbackPromise::PromiseListAllConfigByInfo > PromiseListAllConfigByInfoPtr;

        ConfigPrxCallbackPromise(const promise::Promise< ConfigPrxCallbackPromise::PromiseListAllConfigByInfoPtr > &promise)
        : _promise_ListAllConfigByInfo(promise)
        {}
        
        virtual void callback_ListAllConfigByInfo(const ConfigPrxCallbackPromise::PromiseListAllConfigByInfoPtr &ptr)
        {
            _promise_ListAllConfigByInfo.setValue(ptr);
        }
        virtual void callback_ListAllConfigByInfo_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:ListAllConfigByInfo_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_ListAllConfigByInfo.setException(promise::copyException(str, ret));
        }

    protected:
        promise::Promise< ConfigPrxCallbackPromise::PromiseListAllConfigByInfoPtr > _promise_ListAllConfigByInfo;

    public:
        struct PromiseListConfig: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            vector<std::string> vf;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< ConfigPrxCallbackPromise::PromiseListConfig > PromiseListConfigPtr;

        ConfigPrxCallbackPromise(const promise::Promise< ConfigPrxCallbackPromise::PromiseListConfigPtr > &promise)
        : _promise_ListConfig(promise)
        {}
        
        virtual void callback_ListConfig(const ConfigPrxCallbackPromise::PromiseListConfigPtr &ptr)
        {
            _promise_ListConfig.setValue(ptr);
        }
        virtual void callback_ListConfig_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:ListConfig_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_ListConfig.setException(promise::copyException(str, ret));
        }

    protected:
        promise::Promise< ConfigPrxCallbackPromise::PromiseListConfigPtr > _promise_ListConfig;

    public:
        struct PromiseListConfigByInfo: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            vector<std::string> vf;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< ConfigPrxCallbackPromise::PromiseListConfigByInfo > PromiseListConfigByInfoPtr;

        ConfigPrxCallbackPromise(const promise::Promise< ConfigPrxCallbackPromise::PromiseListConfigByInfoPtr > &promise)
        : _promise_ListConfigByInfo(promise)
        {}
        
        virtual void callback_ListConfigByInfo(const ConfigPrxCallbackPromise::PromiseListConfigByInfoPtr &ptr)
        {
            _promise_ListConfigByInfo.setValue(ptr);
        }
        virtual void callback_ListConfigByInfo_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:ListConfigByInfo_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_ListConfigByInfo.setException(promise::copyException(str, ret));
        }

    protected:
        promise::Promise< ConfigPrxCallbackPromise::PromiseListConfigByInfoPtr > _promise_ListConfigByInfo;

    public:
        struct PromisecheckConfig: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            std::string result;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< ConfigPrxCallbackPromise::PromisecheckConfig > PromisecheckConfigPtr;

        ConfigPrxCallbackPromise(const promise::Promise< ConfigPrxCallbackPromise::PromisecheckConfigPtr > &promise)
        : _promise_checkConfig(promise)
        {}
        
        virtual void callback_checkConfig(const ConfigPrxCallbackPromise::PromisecheckConfigPtr &ptr)
        {
            _promise_checkConfig.setValue(ptr);
        }
        virtual void callback_checkConfig_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:checkConfig_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_checkConfig.setException(promise::copyException(str, ret));
        }

    protected:
        promise::Promise< ConfigPrxCallbackPromise::PromisecheckConfigPtr > _promise_checkConfig;

    public:
        struct PromisecheckConfigByInfo: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            std::string result;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< ConfigPrxCallbackPromise::PromisecheckConfigByInfo > PromisecheckConfigByInfoPtr;

        ConfigPrxCallbackPromise(const promise::Promise< ConfigPrxCallbackPromise::PromisecheckConfigByInfoPtr > &promise)
        : _promise_checkConfigByInfo(promise)
        {}
        
        virtual void callback_checkConfigByInfo(const ConfigPrxCallbackPromise::PromisecheckConfigByInfoPtr &ptr)
        {
            _promise_checkConfigByInfo.setValue(ptr);
        }
        virtual void callback_checkConfigByInfo_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:checkConfigByInfo_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_checkConfigByInfo.setException(promise::copyException(str, ret));
        }

    protected:
        promise::Promise< ConfigPrxCallbackPromise::PromisecheckConfigByInfoPtr > _promise_checkConfigByInfo;

    public:
        struct PromiseloadConfig: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            std::string config;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< ConfigPrxCallbackPromise::PromiseloadConfig > PromiseloadConfigPtr;

        ConfigPrxCallbackPromise(const promise::Promise< ConfigPrxCallbackPromise::PromiseloadConfigPtr > &promise)
        : _promise_loadConfig(promise)
        {}
        
        virtual void callback_loadConfig(const ConfigPrxCallbackPromise::PromiseloadConfigPtr &ptr)
        {
            _promise_loadConfig.setValue(ptr);
        }
        virtual void callback_loadConfig_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:loadConfig_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_loadConfig.setException(promise::copyException(str, ret));
        }

    protected:
        promise::Promise< ConfigPrxCallbackPromise::PromiseloadConfigPtr > _promise_loadConfig;

    public:
        struct PromiseloadConfigByHost: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            std::string config;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< ConfigPrxCallbackPromise::PromiseloadConfigByHost > PromiseloadConfigByHostPtr;

        ConfigPrxCallbackPromise(const promise::Promise< ConfigPrxCallbackPromise::PromiseloadConfigByHostPtr > &promise)
        : _promise_loadConfigByHost(promise)
        {}
        
        virtual void callback_loadConfigByHost(const ConfigPrxCallbackPromise::PromiseloadConfigByHostPtr &ptr)
        {
            _promise_loadConfigByHost.setValue(ptr);
        }
        virtual void callback_loadConfigByHost_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:loadConfigByHost_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_loadConfigByHost.setException(promise::copyException(str, ret));
        }

    protected:
        promise::Promise< ConfigPrxCallbackPromise::PromiseloadConfigByHostPtr > _promise_loadConfigByHost;

    public:
        struct PromiseloadConfigByInfo: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            std::string config;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< ConfigPrxCallbackPromise::PromiseloadConfigByInfo > PromiseloadConfigByInfoPtr;

        ConfigPrxCallbackPromise(const promise::Promise< ConfigPrxCallbackPromise::PromiseloadConfigByInfoPtr > &promise)
        : _promise_loadConfigByInfo(promise)
        {}
        
        virtual void callback_loadConfigByInfo(const ConfigPrxCallbackPromise::PromiseloadConfigByInfoPtr &ptr)
        {
            _promise_loadConfigByInfo.setValue(ptr);
        }
        virtual void callback_loadConfigByInfo_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:loadConfigByInfo_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_loadConfigByInfo.setException(promise::copyException(str, ret));
        }

    protected:
        promise::Promise< ConfigPrxCallbackPromise::PromiseloadConfigByInfoPtr > _promise_loadConfigByInfo;

    public:
        virtual int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __Config_all[]=
            {
                "ListAllConfigByInfo",
                "ListConfig",
                "ListConfigByInfo",
                "checkConfig",
                "checkConfigByInfo",
                "loadConfig",
                "loadConfigByHost",
                "loadConfigByInfo"
            };

            pair<string*, string*> r = equal_range(__Config_all, __Config_all+8, string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __Config_all)
            {
                case 0:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_ListAllConfigByInfo_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);

                    ConfigPrxCallbackPromise::PromiseListAllConfigByInfoPtr ptr = new ConfigPrxCallbackPromise::PromiseListAllConfigByInfo();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->vf, 2, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_ListAllConfigByInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_ListAllConfigByInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response.context;

                    callback_ListAllConfigByInfo(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_ListConfig_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);

                    ConfigPrxCallbackPromise::PromiseListConfigPtr ptr = new ConfigPrxCallbackPromise::PromiseListConfig();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->vf, 3, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_ListConfig_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_ListConfig_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response.context;

                    callback_ListConfig(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_ListConfigByInfo_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);

                    ConfigPrxCallbackPromise::PromiseListConfigByInfoPtr ptr = new ConfigPrxCallbackPromise::PromiseListConfigByInfo();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->vf, 2, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_ListConfigByInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_ListConfigByInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response.context;

                    callback_ListConfigByInfo(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_checkConfig_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);

                    ConfigPrxCallbackPromise::PromisecheckConfigPtr ptr = new ConfigPrxCallbackPromise::PromisecheckConfig();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->result, 4, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_checkConfig_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_checkConfig_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response.context;

                    callback_checkConfig(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 4:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_checkConfigByInfo_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);

                    ConfigPrxCallbackPromise::PromisecheckConfigByInfoPtr ptr = new ConfigPrxCallbackPromise::PromisecheckConfigByInfo();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->result, 2, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_checkConfigByInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_checkConfigByInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response.context;

                    callback_checkConfigByInfo(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 5:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_loadConfig_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);

                    ConfigPrxCallbackPromise::PromiseloadConfigPtr ptr = new ConfigPrxCallbackPromise::PromiseloadConfig();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->config, 4, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_loadConfig_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_loadConfig_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response.context;

                    callback_loadConfig(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 6:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_loadConfigByHost_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);

                    ConfigPrxCallbackPromise::PromiseloadConfigByHostPtr ptr = new ConfigPrxCallbackPromise::PromiseloadConfigByHost();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->config, 4, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_loadConfigByHost_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_loadConfigByHost_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response.context;

                    callback_loadConfigByHost(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 7:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_loadConfigByInfo_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);

                    ConfigPrxCallbackPromise::PromiseloadConfigByInfoPtr ptr = new ConfigPrxCallbackPromise::PromiseloadConfigByInfo();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->config, 2, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_loadConfigByInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_loadConfigByInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response.context;

                    callback_loadConfigByInfo(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<ConfigPrxCallbackPromise> ConfigPrxCallbackPromisePtr;

    /* callback of coroutine async proxy for client */
    class ConfigCoroPrxCallback: public ConfigPrxCallback
    {
    public:
        virtual ~ConfigCoroPrxCallback(){}
    public:
        virtual const map<std::string, std::string> & getResponseContext() const { return _mRspContext; }

        virtual void setResponseContext(const map<std::string, std::string> &mContext) { _mRspContext = mContext; }

    public:
        int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __Config_all[]=
            {
                "ListAllConfigByInfo",
                "ListConfig",
                "ListConfigByInfo",
                "checkConfig",
                "checkConfigByInfo",
                "loadConfig",
                "loadConfigByHost",
                "loadConfigByInfo"
            };

            pair<string*, string*> r = equal_range(__Config_all, __Config_all+8, string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __Config_all)
            {
                case 0:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_ListAllConfigByInfo_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        vector<std::string> vf;
                        _is.read(vf, 2, true);
                        setResponseContext(msg->response.context);

                        callback_ListAllConfigByInfo(_ret, vf);

                    }
                    catch(std::exception &ex)
                    {
                        callback_ListAllConfigByInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_ListAllConfigByInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_ListConfig_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        vector<std::string> vf;
                        _is.read(vf, 3, true);
                        setResponseContext(msg->response.context);

                        callback_ListConfig(_ret, vf);

                    }
                    catch(std::exception &ex)
                    {
                        callback_ListConfig_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_ListConfig_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_ListConfigByInfo_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        vector<std::string> vf;
                        _is.read(vf, 2, true);
                        setResponseContext(msg->response.context);

                        callback_ListConfigByInfo(_ret, vf);

                    }
                    catch(std::exception &ex)
                    {
                        callback_ListConfigByInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_ListConfigByInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_checkConfig_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        std::string result;
                        _is.read(result, 4, true);
                        setResponseContext(msg->response.context);

                        callback_checkConfig(_ret, result);

                    }
                    catch(std::exception &ex)
                    {
                        callback_checkConfig_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_checkConfig_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 4:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_checkConfigByInfo_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        std::string result;
                        _is.read(result, 2, true);
                        setResponseContext(msg->response.context);

                        callback_checkConfigByInfo(_ret, result);

                    }
                    catch(std::exception &ex)
                    {
                        callback_checkConfigByInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_checkConfigByInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 5:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_loadConfig_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        std::string config;
                        _is.read(config, 4, true);
                        setResponseContext(msg->response.context);

                        callback_loadConfig(_ret, config);

                    }
                    catch(std::exception &ex)
                    {
                        callback_loadConfig_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_loadConfig_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 6:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_loadConfigByHost_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        std::string config;
                        _is.read(config, 4, true);
                        setResponseContext(msg->response.context);

                        callback_loadConfigByHost(_ret, config);

                    }
                    catch(std::exception &ex)
                    {
                        callback_loadConfigByHost_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_loadConfigByHost_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 7:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_loadConfigByInfo_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        std::string config;
                        _is.read(config, 2, true);
                        setResponseContext(msg->response.context);

                        callback_loadConfigByInfo(_ret, config);

                    }
                    catch(std::exception &ex)
                    {
                        callback_loadConfigByInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_loadConfigByInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    protected:
        map<std::string, std::string> _mRspContext;
    };
    typedef tars::TC_AutoPtr<ConfigCoroPrxCallback> ConfigCoroPrxCallbackPtr;

    /* proxy for client */
    class ConfigProxy : public tars::ServantProxy
    {
    public:
        typedef map<string, string> TARS_CONTEXT;
        tars::Int32 ListAllConfigByInfo(const tars::GetConfigListInfo & configInfo,vector<std::string> &vf,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(configInfo, 1);
            _os.write(vf, 2);
            tars::ResponsePacket rep;
            std::map<string, string> _mStatus;
            tars_invoke(tars::TARSNORMAL,"ListAllConfigByInfo", _os.getByteBuffer(), context, _mStatus, rep);
            if(pResponseContext)
            {
                *pResponseContext = rep.context;
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep.sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(vf, 2, true);
            return _ret;
        }

        void async_ListAllConfigByInfo(ConfigPrxCallbackPtr callback,const tars::GetConfigListInfo &configInfo,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(configInfo, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"ListAllConfigByInfo", _os.getByteBuffer(), context, _mStatus, callback);
        }
        
        promise::Future< ConfigPrxCallbackPromise::PromiseListAllConfigByInfoPtr > promise_async_ListAllConfigByInfo(const tars::GetConfigListInfo &configInfo,const map<string, string>& context)
        {
            promise::Promise< ConfigPrxCallbackPromise::PromiseListAllConfigByInfoPtr > promise;
            ConfigPrxCallbackPromisePtr callback = new ConfigPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(configInfo, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"ListAllConfigByInfo", _os.getByteBuffer(), context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_ListAllConfigByInfo(ConfigCoroPrxCallbackPtr callback,const tars::GetConfigListInfo &configInfo,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(configInfo, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"ListAllConfigByInfo", _os.getByteBuffer(), context, _mStatus, callback, true);
        }

        tars::Int32 ListConfig(const std::string & app,const std::string & server,vector<std::string> &vf,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(app, 1);
            _os.write(server, 2);
            _os.write(vf, 3);
            tars::ResponsePacket rep;
            std::map<string, string> _mStatus;
            tars_invoke(tars::TARSNORMAL,"ListConfig", _os.getByteBuffer(), context, _mStatus, rep);
            if(pResponseContext)
            {
                *pResponseContext = rep.context;
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep.sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(vf, 3, true);
            return _ret;
        }

        void async_ListConfig(ConfigPrxCallbackPtr callback,const std::string &app,const std::string &server,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(app, 1);
            _os.write(server, 2);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"ListConfig", _os.getByteBuffer(), context, _mStatus, callback);
        }
        
        promise::Future< ConfigPrxCallbackPromise::PromiseListConfigPtr > promise_async_ListConfig(const std::string &app,const std::string &server,const map<string, string>& context)
        {
            promise::Promise< ConfigPrxCallbackPromise::PromiseListConfigPtr > promise;
            ConfigPrxCallbackPromisePtr callback = new ConfigPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(app, 1);
            _os.write(server, 2);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"ListConfig", _os.getByteBuffer(), context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_ListConfig(ConfigCoroPrxCallbackPtr callback,const std::string &app,const std::string &server,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(app, 1);
            _os.write(server, 2);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"ListConfig", _os.getByteBuffer(), context, _mStatus, callback, true);
        }

        tars::Int32 ListConfigByInfo(const tars::ConfigInfo & configInfo,vector<std::string> &vf,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(configInfo, 1);
            _os.write(vf, 2);
            tars::ResponsePacket rep;
            std::map<string, string> _mStatus;
            tars_invoke(tars::TARSNORMAL,"ListConfigByInfo", _os.getByteBuffer(), context, _mStatus, rep);
            if(pResponseContext)
            {
                *pResponseContext = rep.context;
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep.sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(vf, 2, true);
            return _ret;
        }

        void async_ListConfigByInfo(ConfigPrxCallbackPtr callback,const tars::ConfigInfo &configInfo,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(configInfo, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"ListConfigByInfo", _os.getByteBuffer(), context, _mStatus, callback);
        }
        
        promise::Future< ConfigPrxCallbackPromise::PromiseListConfigByInfoPtr > promise_async_ListConfigByInfo(const tars::ConfigInfo &configInfo,const map<string, string>& context)
        {
            promise::Promise< ConfigPrxCallbackPromise::PromiseListConfigByInfoPtr > promise;
            ConfigPrxCallbackPromisePtr callback = new ConfigPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(configInfo, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"ListConfigByInfo", _os.getByteBuffer(), context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_ListConfigByInfo(ConfigCoroPrxCallbackPtr callback,const tars::ConfigInfo &configInfo,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(configInfo, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"ListConfigByInfo", _os.getByteBuffer(), context, _mStatus, callback, true);
        }

        tars::Int32 checkConfig(const std::string & appServerName,const std::string & filename,const std::string & host,std::string &result,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(appServerName, 1);
            _os.write(filename, 2);
            _os.write(host, 3);
            _os.write(result, 4);
            tars::ResponsePacket rep;
            std::map<string, string> _mStatus;
            tars_invoke(tars::TARSNORMAL,"checkConfig", _os.getByteBuffer(), context, _mStatus, rep);
            if(pResponseContext)
            {
                *pResponseContext = rep.context;
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep.sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(result, 4, true);
            return _ret;
        }

        void async_checkConfig(ConfigPrxCallbackPtr callback,const std::string &appServerName,const std::string &filename,const std::string &host,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(appServerName, 1);
            _os.write(filename, 2);
            _os.write(host, 3);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"checkConfig", _os.getByteBuffer(), context, _mStatus, callback);
        }
        
        promise::Future< ConfigPrxCallbackPromise::PromisecheckConfigPtr > promise_async_checkConfig(const std::string &appServerName,const std::string &filename,const std::string &host,const map<string, string>& context)
        {
            promise::Promise< ConfigPrxCallbackPromise::PromisecheckConfigPtr > promise;
            ConfigPrxCallbackPromisePtr callback = new ConfigPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(appServerName, 1);
            _os.write(filename, 2);
            _os.write(host, 3);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"checkConfig", _os.getByteBuffer(), context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_checkConfig(ConfigCoroPrxCallbackPtr callback,const std::string &appServerName,const std::string &filename,const std::string &host,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(appServerName, 1);
            _os.write(filename, 2);
            _os.write(host, 3);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"checkConfig", _os.getByteBuffer(), context, _mStatus, callback, true);
        }

        tars::Int32 checkConfigByInfo(const tars::ConfigInfo & configInfo,std::string &result,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(configInfo, 1);
            _os.write(result, 2);
            tars::ResponsePacket rep;
            std::map<string, string> _mStatus;
            tars_invoke(tars::TARSNORMAL,"checkConfigByInfo", _os.getByteBuffer(), context, _mStatus, rep);
            if(pResponseContext)
            {
                *pResponseContext = rep.context;
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep.sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(result, 2, true);
            return _ret;
        }

        void async_checkConfigByInfo(ConfigPrxCallbackPtr callback,const tars::ConfigInfo &configInfo,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(configInfo, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"checkConfigByInfo", _os.getByteBuffer(), context, _mStatus, callback);
        }
        
        promise::Future< ConfigPrxCallbackPromise::PromisecheckConfigByInfoPtr > promise_async_checkConfigByInfo(const tars::ConfigInfo &configInfo,const map<string, string>& context)
        {
            promise::Promise< ConfigPrxCallbackPromise::PromisecheckConfigByInfoPtr > promise;
            ConfigPrxCallbackPromisePtr callback = new ConfigPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(configInfo, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"checkConfigByInfo", _os.getByteBuffer(), context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_checkConfigByInfo(ConfigCoroPrxCallbackPtr callback,const tars::ConfigInfo &configInfo,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(configInfo, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"checkConfigByInfo", _os.getByteBuffer(), context, _mStatus, callback, true);
        }

        tars::Int32 loadConfig(const std::string & app,const std::string & server,const std::string & filename,std::string &config,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(app, 1);
            _os.write(server, 2);
            _os.write(filename, 3);
            _os.write(config, 4);
            tars::ResponsePacket rep;
            std::map<string, string> _mStatus;
            tars_invoke(tars::TARSNORMAL,"loadConfig", _os.getByteBuffer(), context, _mStatus, rep);
            if(pResponseContext)
            {
                *pResponseContext = rep.context;
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep.sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(config, 4, true);
            return _ret;
        }

        void async_loadConfig(ConfigPrxCallbackPtr callback,const std::string &app,const std::string &server,const std::string &filename,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(app, 1);
            _os.write(server, 2);
            _os.write(filename, 3);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"loadConfig", _os.getByteBuffer(), context, _mStatus, callback);
        }
        
        promise::Future< ConfigPrxCallbackPromise::PromiseloadConfigPtr > promise_async_loadConfig(const std::string &app,const std::string &server,const std::string &filename,const map<string, string>& context)
        {
            promise::Promise< ConfigPrxCallbackPromise::PromiseloadConfigPtr > promise;
            ConfigPrxCallbackPromisePtr callback = new ConfigPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(app, 1);
            _os.write(server, 2);
            _os.write(filename, 3);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"loadConfig", _os.getByteBuffer(), context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_loadConfig(ConfigCoroPrxCallbackPtr callback,const std::string &app,const std::string &server,const std::string &filename,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(app, 1);
            _os.write(server, 2);
            _os.write(filename, 3);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"loadConfig", _os.getByteBuffer(), context, _mStatus, callback, true);
        }

        tars::Int32 loadConfigByHost(const std::string & appServerName,const std::string & filename,const std::string & host,std::string &config,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(appServerName, 1);
            _os.write(filename, 2);
            _os.write(host, 3);
            _os.write(config, 4);
            tars::ResponsePacket rep;
            std::map<string, string> _mStatus;
            tars_invoke(tars::TARSNORMAL,"loadConfigByHost", _os.getByteBuffer(), context, _mStatus, rep);
            if(pResponseContext)
            {
                *pResponseContext = rep.context;
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep.sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(config, 4, true);
            return _ret;
        }

        void async_loadConfigByHost(ConfigPrxCallbackPtr callback,const std::string &appServerName,const std::string &filename,const std::string &host,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(appServerName, 1);
            _os.write(filename, 2);
            _os.write(host, 3);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"loadConfigByHost", _os.getByteBuffer(), context, _mStatus, callback);
        }
        
        promise::Future< ConfigPrxCallbackPromise::PromiseloadConfigByHostPtr > promise_async_loadConfigByHost(const std::string &appServerName,const std::string &filename,const std::string &host,const map<string, string>& context)
        {
            promise::Promise< ConfigPrxCallbackPromise::PromiseloadConfigByHostPtr > promise;
            ConfigPrxCallbackPromisePtr callback = new ConfigPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(appServerName, 1);
            _os.write(filename, 2);
            _os.write(host, 3);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"loadConfigByHost", _os.getByteBuffer(), context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_loadConfigByHost(ConfigCoroPrxCallbackPtr callback,const std::string &appServerName,const std::string &filename,const std::string &host,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(appServerName, 1);
            _os.write(filename, 2);
            _os.write(host, 3);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"loadConfigByHost", _os.getByteBuffer(), context, _mStatus, callback, true);
        }

        tars::Int32 loadConfigByInfo(const tars::ConfigInfo & configInfo,std::string &config,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(configInfo, 1);
            _os.write(config, 2);
            tars::ResponsePacket rep;
            std::map<string, string> _mStatus;
            tars_invoke(tars::TARSNORMAL,"loadConfigByInfo", _os.getByteBuffer(), context, _mStatus, rep);
            if(pResponseContext)
            {
                *pResponseContext = rep.context;
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep.sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(config, 2, true);
            return _ret;
        }

        void async_loadConfigByInfo(ConfigPrxCallbackPtr callback,const tars::ConfigInfo &configInfo,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(configInfo, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"loadConfigByInfo", _os.getByteBuffer(), context, _mStatus, callback);
        }
        
        promise::Future< ConfigPrxCallbackPromise::PromiseloadConfigByInfoPtr > promise_async_loadConfigByInfo(const tars::ConfigInfo &configInfo,const map<string, string>& context)
        {
            promise::Promise< ConfigPrxCallbackPromise::PromiseloadConfigByInfoPtr > promise;
            ConfigPrxCallbackPromisePtr callback = new ConfigPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(configInfo, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"loadConfigByInfo", _os.getByteBuffer(), context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_loadConfigByInfo(ConfigCoroPrxCallbackPtr callback,const tars::ConfigInfo &configInfo,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(configInfo, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"loadConfigByInfo", _os.getByteBuffer(), context, _mStatus, callback, true);
        }

        ConfigProxy* tars_hash(int64_t key)
        {
            return (ConfigProxy*)ServantProxy::tars_hash(key);
        }

        ConfigProxy* tars_consistent_hash(int64_t key)
        {
            return (ConfigProxy*)ServantProxy::tars_consistent_hash(key);
        }

        ConfigProxy* tars_set_timeout(int msecond)
        {
            return (ConfigProxy*)ServantProxy::tars_set_timeout(msecond);
        }

    };
    typedef tars::TC_AutoPtr<ConfigProxy> ConfigPrx;

    /* servant for server */
    class Config : public tars::Servant
    {
    public:
        virtual ~Config(){}
        virtual tars::Int32 ListAllConfigByInfo(const tars::GetConfigListInfo & configInfo,vector<std::string> &vf,tars::TarsCurrentPtr current) = 0;
        static void async_response_ListAllConfigByInfo(tars::TarsCurrentPtr current, tars::Int32 _ret, const vector<std::string> &vf)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("vf", vf);

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriter> _os;
                _os.write(_ret, 0);

                _os.write(vf, 2);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual tars::Int32 ListConfig(const std::string & app,const std::string & server,vector<std::string> &vf,tars::TarsCurrentPtr current) = 0;
        static void async_response_ListConfig(tars::TarsCurrentPtr current, tars::Int32 _ret, const vector<std::string> &vf)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("vf", vf);

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriter> _os;
                _os.write(_ret, 0);

                _os.write(vf, 3);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual tars::Int32 ListConfigByInfo(const tars::ConfigInfo & configInfo,vector<std::string> &vf,tars::TarsCurrentPtr current) = 0;
        static void async_response_ListConfigByInfo(tars::TarsCurrentPtr current, tars::Int32 _ret, const vector<std::string> &vf)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("vf", vf);

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriter> _os;
                _os.write(_ret, 0);

                _os.write(vf, 2);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual tars::Int32 checkConfig(const std::string & appServerName,const std::string & filename,const std::string & host,std::string &result,tars::TarsCurrentPtr current) = 0;
        static void async_response_checkConfig(tars::TarsCurrentPtr current, tars::Int32 _ret, const std::string &result)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("result", result);

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriter> _os;
                _os.write(_ret, 0);

                _os.write(result, 4);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual tars::Int32 checkConfigByInfo(const tars::ConfigInfo & configInfo,std::string &result,tars::TarsCurrentPtr current) = 0;
        static void async_response_checkConfigByInfo(tars::TarsCurrentPtr current, tars::Int32 _ret, const std::string &result)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("result", result);

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriter> _os;
                _os.write(_ret, 0);

                _os.write(result, 2);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual tars::Int32 loadConfig(const std::string & app,const std::string & server,const std::string & filename,std::string &config,tars::TarsCurrentPtr current) = 0;
        static void async_response_loadConfig(tars::TarsCurrentPtr current, tars::Int32 _ret, const std::string &config)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("config", config);

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriter> _os;
                _os.write(_ret, 0);

                _os.write(config, 4);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual tars::Int32 loadConfigByHost(const std::string & appServerName,const std::string & filename,const std::string & host,std::string &config,tars::TarsCurrentPtr current) = 0;
        static void async_response_loadConfigByHost(tars::TarsCurrentPtr current, tars::Int32 _ret, const std::string &config)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("config", config);

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriter> _os;
                _os.write(_ret, 0);

                _os.write(config, 4);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual tars::Int32 loadConfigByInfo(const tars::ConfigInfo & configInfo,std::string &config,tars::TarsCurrentPtr current) = 0;
        static void async_response_loadConfigByInfo(tars::TarsCurrentPtr current, tars::Int32 _ret, const std::string &config)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("config", config);

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriter> _os;
                _os.write(_ret, 0);

                _os.write(config, 2);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

    public:
        int onDispatch(tars::TarsCurrentPtr _current, vector<char> &_sResponseBuffer)
        {
            static ::std::string __tars__Config_all[]=
            {
                "ListAllConfigByInfo",
                "ListConfig",
                "ListConfigByInfo",
                "checkConfig",
                "checkConfigByInfo",
                "loadConfig",
                "loadConfigByHost",
                "loadConfigByInfo"
            };

            pair<string*, string*> r = equal_range(__tars__Config_all, __tars__Config_all+8, _current->getFuncName());
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __tars__Config_all)
            {
                case 0:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    tars::GetConfigListInfo configInfo;
                    vector<std::string> vf;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("configInfo", configInfo);
                        tarsAttr.getByDefault("vf", vf, vf);
                    }
                    else
                    {
                        _is.read(configInfo, 1, true);
                        _is.read(vf, 2, false);
                    }
                    tars::Int32 _ret = ListAllConfigByInfo(configInfo,vf, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION )
                        {
                            UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("vf", vf);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriter> _os;
                            _os.write(_ret, 0);
                            _os.write(vf, 2);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string app;
                    std::string server;
                    vector<std::string> vf;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("app", app);
                        tarsAttr.get("server", server);
                        tarsAttr.getByDefault("vf", vf, vf);
                    }
                    else
                    {
                        _is.read(app, 1, true);
                        _is.read(server, 2, true);
                        _is.read(vf, 3, false);
                    }
                    tars::Int32 _ret = ListConfig(app,server,vf, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION )
                        {
                            UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("vf", vf);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriter> _os;
                            _os.write(_ret, 0);
                            _os.write(vf, 3);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    tars::ConfigInfo configInfo;
                    vector<std::string> vf;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("configInfo", configInfo);
                        tarsAttr.getByDefault("vf", vf, vf);
                    }
                    else
                    {
                        _is.read(configInfo, 1, true);
                        _is.read(vf, 2, false);
                    }
                    tars::Int32 _ret = ListConfigByInfo(configInfo,vf, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION )
                        {
                            UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("vf", vf);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriter> _os;
                            _os.write(_ret, 0);
                            _os.write(vf, 2);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string appServerName;
                    std::string filename;
                    std::string host;
                    std::string result;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("appServerName", appServerName);
                        tarsAttr.get("filename", filename);
                        tarsAttr.get("host", host);
                        tarsAttr.getByDefault("result", result, result);
                    }
                    else
                    {
                        _is.read(appServerName, 1, true);
                        _is.read(filename, 2, true);
                        _is.read(host, 3, true);
                        _is.read(result, 4, false);
                    }
                    tars::Int32 _ret = checkConfig(appServerName,filename,host,result, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION )
                        {
                            UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("result", result);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriter> _os;
                            _os.write(_ret, 0);
                            _os.write(result, 4);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 4:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    tars::ConfigInfo configInfo;
                    std::string result;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("configInfo", configInfo);
                        tarsAttr.getByDefault("result", result, result);
                    }
                    else
                    {
                        _is.read(configInfo, 1, true);
                        _is.read(result, 2, false);
                    }
                    tars::Int32 _ret = checkConfigByInfo(configInfo,result, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION )
                        {
                            UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("result", result);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriter> _os;
                            _os.write(_ret, 0);
                            _os.write(result, 2);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 5:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string app;
                    std::string server;
                    std::string filename;
                    std::string config;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("app", app);
                        tarsAttr.get("server", server);
                        tarsAttr.get("filename", filename);
                        tarsAttr.getByDefault("config", config, config);
                    }
                    else
                    {
                        _is.read(app, 1, true);
                        _is.read(server, 2, true);
                        _is.read(filename, 3, true);
                        _is.read(config, 4, false);
                    }
                    tars::Int32 _ret = loadConfig(app,server,filename,config, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION )
                        {
                            UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("config", config);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriter> _os;
                            _os.write(_ret, 0);
                            _os.write(config, 4);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 6:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string appServerName;
                    std::string filename;
                    std::string host;
                    std::string config;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("appServerName", appServerName);
                        tarsAttr.get("filename", filename);
                        tarsAttr.get("host", host);
                        tarsAttr.getByDefault("config", config, config);
                    }
                    else
                    {
                        _is.read(appServerName, 1, true);
                        _is.read(filename, 2, true);
                        _is.read(host, 3, true);
                        _is.read(config, 4, false);
                    }
                    tars::Int32 _ret = loadConfigByHost(appServerName,filename,host,config, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION )
                        {
                            UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("config", config);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriter> _os;
                            _os.write(_ret, 0);
                            _os.write(config, 4);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 7:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    tars::ConfigInfo configInfo;
                    std::string config;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("configInfo", configInfo);
                        tarsAttr.getByDefault("config", config, config);
                    }
                    else
                    {
                        _is.read(configInfo, 1, true);
                        _is.read(config, 2, false);
                    }
                    tars::Int32 _ret = loadConfigByInfo(configInfo,config, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION )
                        {
                            UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("config", config);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriter> _os;
                            _os.write(_ret, 0);
                            _os.write(config, 2);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }
    };


}



#endif
