// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

#ifndef __NOTIFYF_H_
#define __NOTIFYF_H_

#include <map>
#include <string>
#include <vector>
#include "tup/Tars.h"
using namespace std;
#include "servant/ServantProxy.h"
#include "servant/Servant.h"
#include "promise/promise.h"


namespace tars
{
    enum NOTIFYLEVEL
    {
        NOTIFYNORMAL,
        NOTIFYWARN,
        NOTIFYERROR,
    };
    inline string etos(const NOTIFYLEVEL & e)
    {
        switch(e)
        {
            case NOTIFYNORMAL: return "NOTIFYNORMAL";
            case NOTIFYWARN: return "NOTIFYWARN";
            case NOTIFYERROR: return "NOTIFYERROR";
            default: return "";
        }
    }
    inline int stoe(const string & s, NOTIFYLEVEL & e)
    {
        if(s == "NOTIFYNORMAL")  { e=NOTIFYNORMAL; return 0;}
        if(s == "NOTIFYWARN")  { e=NOTIFYWARN; return 0;}
        if(s == "NOTIFYERROR")  { e=NOTIFYERROR; return 0;}

        return -1;
    }

    enum ReportType
    {
        REPORT,
        NOTIFY,
    };
    inline string etos(const ReportType & e)
    {
        switch(e)
        {
            case REPORT: return "REPORT";
            case NOTIFY: return "NOTIFY";
            default: return "";
        }
    }
    inline int stoe(const string & s, ReportType & e)
    {
        if(s == "REPORT")  { e=REPORT; return 0;}
        if(s == "NOTIFY")  { e=NOTIFY; return 0;}

        return -1;
    }

    struct NotifyKey : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.NotifyKey";
        }
        static string MD5()
        {
            return "074644cababcb11e8f54e9fdc06346f2";
        }
        NotifyKey()
        :name(""),ip(""),page(0)
        {
        }
        void resetDefautlt()
        {
            name = "";
            ip = "";
            page = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(name, 1);
            _os.write(ip, 2);
            _os.write(page, 3);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(name, 1, true);
            _is.read(ip, 2, true);
            _is.read(page, 3, true);
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(name,"name");
            _ds.display(ip,"ip");
            _ds.display(page,"page");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(name, true);
            _ds.displaySimple(ip, true);
            _ds.displaySimple(page, false);
            return _os;
        }
    public:
        std::string name;
        std::string ip;
        tars::Int32 page;
    };
    inline bool operator==(const NotifyKey&l, const NotifyKey&r)
    {
        return l.name == r.name && l.ip == r.ip && l.page == r.page;
    }
    inline bool operator!=(const NotifyKey&l, const NotifyKey&r)
    {
        return !(l == r);
    }

    struct NotifyItem : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.NotifyItem";
        }
        static string MD5()
        {
            return "34368b1d85d52126f8efa6e27af8f151";
        }
        NotifyItem()
        :sTimeStamp(""),sServerId(""),iLevel(0),sMessage("")
        {
        }
        void resetDefautlt()
        {
            sTimeStamp = "";
            sServerId = "";
            iLevel = 0;
            sMessage = "";
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(sTimeStamp, 1);
            _os.write(sServerId, 2);
            _os.write(iLevel, 3);
            _os.write(sMessage, 4);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(sTimeStamp, 1, true);
            _is.read(sServerId, 2, true);
            _is.read(iLevel, 3, true);
            _is.read(sMessage, 4, true);
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(sTimeStamp,"sTimeStamp");
            _ds.display(sServerId,"sServerId");
            _ds.display(iLevel,"iLevel");
            _ds.display(sMessage,"sMessage");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(sTimeStamp, true);
            _ds.displaySimple(sServerId, true);
            _ds.displaySimple(iLevel, true);
            _ds.displaySimple(sMessage, false);
            return _os;
        }
    public:
        std::string sTimeStamp;
        std::string sServerId;
        tars::Int32 iLevel;
        std::string sMessage;
    };
    inline bool operator==(const NotifyItem&l, const NotifyItem&r)
    {
        return l.sTimeStamp == r.sTimeStamp && l.sServerId == r.sServerId && l.iLevel == r.iLevel && l.sMessage == r.sMessage;
    }
    inline bool operator!=(const NotifyItem&l, const NotifyItem&r)
    {
        return !(l == r);
    }

    struct NotifyInfo : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.NotifyInfo";
        }
        static string MD5()
        {
            return "f734511a15b5b9e1dfad29a3363d53c7";
        }
        NotifyInfo()
        :nextpage(0)
        {
        }
        void resetDefautlt()
        {
            nextpage = 0;
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write(nextpage, 1);
            _os.write(notifyItems, 2);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            _is.read(nextpage, 1, true);
            _is.read(notifyItems, 2, true);
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display(nextpage,"nextpage");
            _ds.display(notifyItems,"notifyItems");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple(nextpage, true);
            _ds.displaySimple(notifyItems, false);
            return _os;
        }
    public:
        tars::Int32 nextpage;
        vector<tars::NotifyItem> notifyItems;
    };
    inline bool operator==(const NotifyInfo&l, const NotifyInfo&r)
    {
        return l.nextpage == r.nextpage && l.notifyItems == r.notifyItems;
    }
    inline bool operator!=(const NotifyInfo&l, const NotifyInfo&r)
    {
        return !(l == r);
    }

    struct ReportInfo : public tars::TarsStructBase
    {
    public:
        static string className()
        {
            return "tars.ReportInfo";
        }
        static string MD5()
        {
            return "d239e72086267895c52719b41fce342c";
        }
        ReportInfo()
        :eType(tars::REPORT),sApp(""),sSet(""),sContainer(""),sServer(""),sMessage(""),sThreadId(""),eLevel(tars::NOTIFYNORMAL)
        {
        }
        void resetDefautlt()
        {
            sApp = "";
            sSet = "";
            sContainer = "";
            sServer = "";
            sMessage = "";
            sThreadId = "";
        }
        template<typename WriterT>
        void writeTo(tars::TarsOutputStream<WriterT>& _os) const
        {
            _os.write((tars::Int32)eType, 1);
            _os.write(sApp, 2);
            _os.write(sSet, 3);
            _os.write(sContainer, 4);
            _os.write(sServer, 5);
            _os.write(sMessage, 6);
            if (sThreadId != "")
            {
                _os.write(sThreadId, 7);
            }
            _os.write((tars::Int32)eLevel, 8);
        }
        template<typename ReaderT>
        void readFrom(tars::TarsInputStream<ReaderT>& _is)
        {
            resetDefautlt();
            tars::Int32 eTemp1 = tars::REPORT;
            _is.read(eTemp1, 1, true);
            eType = (tars::ReportType)eTemp1;
            _is.read(sApp, 2, true);
            _is.read(sSet, 3, true);
            _is.read(sContainer, 4, true);
            _is.read(sServer, 5, true);
            _is.read(sMessage, 6, true);
            _is.read(sThreadId, 7, false);
            tars::Int32 eTemp8 = tars::NOTIFYNORMAL;
            _is.read(eTemp8, 8, false);
            eLevel = (tars::NOTIFYLEVEL)eTemp8;
        }
        ostream& display(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.display((tars::Int32)eType,"eType");
            _ds.display(sApp,"sApp");
            _ds.display(sSet,"sSet");
            _ds.display(sContainer,"sContainer");
            _ds.display(sServer,"sServer");
            _ds.display(sMessage,"sMessage");
            _ds.display(sThreadId,"sThreadId");
            _ds.display((tars::Int32)eLevel,"eLevel");
            return _os;
        }
        ostream& displaySimple(ostream& _os, int _level=0) const
        {
            tars::TarsDisplayer _ds(_os, _level);
            _ds.displaySimple((tars::Int32)eType, true);
            _ds.displaySimple(sApp, true);
            _ds.displaySimple(sSet, true);
            _ds.displaySimple(sContainer, true);
            _ds.displaySimple(sServer, true);
            _ds.displaySimple(sMessage, true);
            _ds.displaySimple(sThreadId, true);
            _ds.displaySimple((tars::Int32)eLevel, false);
            return _os;
        }
    public:
        tars::ReportType eType;
        std::string sApp;
        std::string sSet;
        std::string sContainer;
        std::string sServer;
        std::string sMessage;
        std::string sThreadId;
        tars::NOTIFYLEVEL eLevel;
    };
    inline bool operator==(const ReportInfo&l, const ReportInfo&r)
    {
        return l.eType == r.eType && l.sApp == r.sApp && l.sSet == r.sSet && l.sContainer == r.sContainer && l.sServer == r.sServer && l.sMessage == r.sMessage && l.sThreadId == r.sThreadId && l.eLevel == r.eLevel;
    }
    inline bool operator!=(const ReportInfo&l, const ReportInfo&r)
    {
        return !(l == r);
    }


    /* callback of async proxy for client */
    class NotifyPrxCallback: public tars::ServantProxyCallback
    {
    public:
        virtual ~NotifyPrxCallback(){}
        virtual void callback_getNotifyInfo(tars::Int32 ret,  const tars::NotifyInfo& stInfo)
        { throw std::runtime_error("callback_getNotifyInfo() override incorrect."); }
        virtual void callback_getNotifyInfo_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_getNotifyInfo_exception() override incorrect."); }

        virtual void callback_notifyServer()
        { throw std::runtime_error("callback_notifyServer() override incorrect."); }
        virtual void callback_notifyServer_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_notifyServer_exception() override incorrect."); }

        virtual void callback_reportNotifyInfo()
        { throw std::runtime_error("callback_reportNotifyInfo() override incorrect."); }
        virtual void callback_reportNotifyInfo_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_reportNotifyInfo_exception() override incorrect."); }

        virtual void callback_reportServer()
        { throw std::runtime_error("callback_reportServer() override incorrect."); }
        virtual void callback_reportServer_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_reportServer_exception() override incorrect."); }

    public:
        virtual const map<std::string, std::string> & getResponseContext() const
        {
            CallbackThreadData * pCbtd = CallbackThreadData::getData();
            assert(pCbtd != NULL);

            if(!pCbtd->getContextValid())
            {
                throw TC_Exception("cann't get response context");
            }
            return pCbtd->getResponseContext();
        }

    public:
        virtual int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __Notify_all[]=
            {
                "getNotifyInfo",
                "notifyServer",
                "reportNotifyInfo",
                "reportServer"
            };
            pair<string*, string*> r = equal_range(__Notify_all, __Notify_all+4, string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __Notify_all)
            {
                case 0:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_getNotifyInfo_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    tars::NotifyInfo stInfo;
                    _is.read(stInfo, 2, true);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response.context);

                    callback_getNotifyInfo(_ret, stInfo);

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_notifyServer_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response.context);

                    callback_notifyServer();

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_reportNotifyInfo_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response.context);

                    callback_reportNotifyInfo();

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_reportServer_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(msg->response.context);

                    callback_reportServer();

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<NotifyPrxCallback> NotifyPrxCallbackPtr;

    /* callback of promise async proxy for client */
    class NotifyPrxCallbackPromise: public tars::ServantProxyCallback
    {
    public:
        virtual ~NotifyPrxCallbackPromise(){}
    public:
        struct PromisegetNotifyInfo: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            tars::NotifyInfo stInfo;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< NotifyPrxCallbackPromise::PromisegetNotifyInfo > PromisegetNotifyInfoPtr;

        NotifyPrxCallbackPromise(const promise::Promise< NotifyPrxCallbackPromise::PromisegetNotifyInfoPtr > &promise)
        : _promise_getNotifyInfo(promise)
        {}
        
        virtual void callback_getNotifyInfo(const NotifyPrxCallbackPromise::PromisegetNotifyInfoPtr &ptr)
        {
            _promise_getNotifyInfo.setValue(ptr);
        }
        virtual void callback_getNotifyInfo_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:getNotifyInfo_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_getNotifyInfo.setException(promise::copyException(str, ret));
        }

    protected:
        promise::Promise< NotifyPrxCallbackPromise::PromisegetNotifyInfoPtr > _promise_getNotifyInfo;

    public:
        struct PromisenotifyServer: virtual public TC_HandleBase
        {
        public:
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< NotifyPrxCallbackPromise::PromisenotifyServer > PromisenotifyServerPtr;

        NotifyPrxCallbackPromise(const promise::Promise< NotifyPrxCallbackPromise::PromisenotifyServerPtr > &promise)
        : _promise_notifyServer(promise)
        {}
        
        virtual void callback_notifyServer(const NotifyPrxCallbackPromise::PromisenotifyServerPtr &ptr)
        {
            _promise_notifyServer.setValue(ptr);
        }
        virtual void callback_notifyServer_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:notifyServer_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_notifyServer.setException(promise::copyException(str, ret));
        }

    protected:
        promise::Promise< NotifyPrxCallbackPromise::PromisenotifyServerPtr > _promise_notifyServer;

    public:
        struct PromisereportNotifyInfo: virtual public TC_HandleBase
        {
        public:
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< NotifyPrxCallbackPromise::PromisereportNotifyInfo > PromisereportNotifyInfoPtr;

        NotifyPrxCallbackPromise(const promise::Promise< NotifyPrxCallbackPromise::PromisereportNotifyInfoPtr > &promise)
        : _promise_reportNotifyInfo(promise)
        {}
        
        virtual void callback_reportNotifyInfo(const NotifyPrxCallbackPromise::PromisereportNotifyInfoPtr &ptr)
        {
            _promise_reportNotifyInfo.setValue(ptr);
        }
        virtual void callback_reportNotifyInfo_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:reportNotifyInfo_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_reportNotifyInfo.setException(promise::copyException(str, ret));
        }

    protected:
        promise::Promise< NotifyPrxCallbackPromise::PromisereportNotifyInfoPtr > _promise_reportNotifyInfo;

    public:
        struct PromisereportServer: virtual public TC_HandleBase
        {
        public:
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< NotifyPrxCallbackPromise::PromisereportServer > PromisereportServerPtr;

        NotifyPrxCallbackPromise(const promise::Promise< NotifyPrxCallbackPromise::PromisereportServerPtr > &promise)
        : _promise_reportServer(promise)
        {}
        
        virtual void callback_reportServer(const NotifyPrxCallbackPromise::PromisereportServerPtr &ptr)
        {
            _promise_reportServer.setValue(ptr);
        }
        virtual void callback_reportServer_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:reportServer_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_reportServer.setException(promise::copyException(str, ret));
        }

    protected:
        promise::Promise< NotifyPrxCallbackPromise::PromisereportServerPtr > _promise_reportServer;

    public:
        virtual int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __Notify_all[]=
            {
                "getNotifyInfo",
                "notifyServer",
                "reportNotifyInfo",
                "reportServer"
            };

            pair<string*, string*> r = equal_range(__Notify_all, __Notify_all+4, string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __Notify_all)
            {
                case 0:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_getNotifyInfo_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);

                    NotifyPrxCallbackPromise::PromisegetNotifyInfoPtr ptr = new NotifyPrxCallbackPromise::PromisegetNotifyInfo();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->stInfo, 2, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_getNotifyInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_getNotifyInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response.context;

                    callback_getNotifyInfo(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_notifyServer_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);

                    NotifyPrxCallbackPromise::PromisenotifyServerPtr ptr = new NotifyPrxCallbackPromise::PromisenotifyServer();

                    try
                    {
                    }
                    catch(std::exception &ex)
                    {
                        callback_notifyServer_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_notifyServer_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response.context;

                    callback_notifyServer(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_reportNotifyInfo_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);

                    NotifyPrxCallbackPromise::PromisereportNotifyInfoPtr ptr = new NotifyPrxCallbackPromise::PromisereportNotifyInfo();

                    try
                    {
                    }
                    catch(std::exception &ex)
                    {
                        callback_reportNotifyInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_reportNotifyInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response.context;

                    callback_reportNotifyInfo(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_reportServer_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);

                    NotifyPrxCallbackPromise::PromisereportServerPtr ptr = new NotifyPrxCallbackPromise::PromisereportServer();

                    try
                    {
                    }
                    catch(std::exception &ex)
                    {
                        callback_reportServer_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_reportServer_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = msg->response.context;

                    callback_reportServer(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<NotifyPrxCallbackPromise> NotifyPrxCallbackPromisePtr;

    /* callback of coroutine async proxy for client */
    class NotifyCoroPrxCallback: public NotifyPrxCallback
    {
    public:
        virtual ~NotifyCoroPrxCallback(){}
    public:
        virtual const map<std::string, std::string> & getResponseContext() const { return _mRspContext; }

        virtual void setResponseContext(const map<std::string, std::string> &mContext) { _mRspContext = mContext; }

    public:
        int onDispatch(tars::ReqMessagePtr msg)
        {
            static ::std::string __Notify_all[]=
            {
                "getNotifyInfo",
                "notifyServer",
                "reportNotifyInfo",
                "reportServer"
            };

            pair<string*, string*> r = equal_range(__Notify_all, __Notify_all+4, string(msg->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __Notify_all)
            {
                case 0:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_getNotifyInfo_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        tars::NotifyInfo stInfo;
                        _is.read(stInfo, 2, true);
                        setResponseContext(msg->response.context);

                        callback_getNotifyInfo(_ret, stInfo);

                    }
                    catch(std::exception &ex)
                    {
                        callback_getNotifyInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_getNotifyInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_notifyServer_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    try
                    {
                        setResponseContext(msg->response.context);

                        callback_notifyServer();

                    }
                    catch(std::exception &ex)
                    {
                        callback_notifyServer_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_notifyServer_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_reportNotifyInfo_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    try
                    {
                        setResponseContext(msg->response.context);

                        callback_reportNotifyInfo();

                    }
                    catch(std::exception &ex)
                    {
                        callback_reportNotifyInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_reportNotifyInfo_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    if (msg->response.iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_reportServer_exception(msg->response.iRet);

                        return msg->response.iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(msg->response.sBuffer);
                    try
                    {
                        setResponseContext(msg->response.context);

                        callback_reportServer();

                    }
                    catch(std::exception &ex)
                    {
                        callback_reportServer_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_reportServer_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    protected:
        map<std::string, std::string> _mRspContext;
    };
    typedef tars::TC_AutoPtr<NotifyCoroPrxCallback> NotifyCoroPrxCallbackPtr;

    /* proxy for client */
    class NotifyProxy : public tars::ServantProxy
    {
    public:
        typedef map<string, string> TARS_CONTEXT;
        tars::Int32 getNotifyInfo(const tars::NotifyKey & stKey,tars::NotifyInfo &stInfo,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(stKey, 1);
            _os.write(stInfo, 2);
            tars::ResponsePacket rep;
            std::map<string, string> _mStatus;
            tars_invoke(tars::TARSNORMAL,"getNotifyInfo", _os.getByteBuffer(), context, _mStatus, rep);
            if(pResponseContext)
            {
                *pResponseContext = rep.context;
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep.sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(stInfo, 2, true);
            return _ret;
        }

        void async_getNotifyInfo(NotifyPrxCallbackPtr callback,const tars::NotifyKey &stKey,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(stKey, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"getNotifyInfo", _os.getByteBuffer(), context, _mStatus, callback);
        }
        
        promise::Future< NotifyPrxCallbackPromise::PromisegetNotifyInfoPtr > promise_async_getNotifyInfo(const tars::NotifyKey &stKey,const map<string, string>& context)
        {
            promise::Promise< NotifyPrxCallbackPromise::PromisegetNotifyInfoPtr > promise;
            NotifyPrxCallbackPromisePtr callback = new NotifyPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(stKey, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"getNotifyInfo", _os.getByteBuffer(), context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_getNotifyInfo(NotifyCoroPrxCallbackPtr callback,const tars::NotifyKey &stKey,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(stKey, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"getNotifyInfo", _os.getByteBuffer(), context, _mStatus, callback, true);
        }

        void notifyServer(const std::string & sServerName,tars::NOTIFYLEVEL level,const std::string & sMessage,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(sServerName, 1);
            _os.write((tars::Int32)level, 2);
            _os.write(sMessage, 3);
            tars::ResponsePacket rep;
            std::map<string, string> _mStatus;
            tars_invoke(tars::TARSNORMAL,"notifyServer", _os.getByteBuffer(), context, _mStatus, rep);
            if(pResponseContext)
            {
                *pResponseContext = rep.context;
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep.sBuffer);
        }

        void async_notifyServer(NotifyPrxCallbackPtr callback,const std::string &sServerName,tars::NOTIFYLEVEL level,const std::string &sMessage,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(sServerName, 1);
            _os.write((tars::Int32)level, 2);
            _os.write(sMessage, 3);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"notifyServer", _os.getByteBuffer(), context, _mStatus, callback);
        }
        
        promise::Future< NotifyPrxCallbackPromise::PromisenotifyServerPtr > promise_async_notifyServer(const std::string &sServerName,tars::NOTIFYLEVEL level,const std::string &sMessage,const map<string, string>& context)
        {
            promise::Promise< NotifyPrxCallbackPromise::PromisenotifyServerPtr > promise;
            NotifyPrxCallbackPromisePtr callback = new NotifyPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(sServerName, 1);
            _os.write((tars::Int32)level, 2);
            _os.write(sMessage, 3);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"notifyServer", _os.getByteBuffer(), context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_notifyServer(NotifyCoroPrxCallbackPtr callback,const std::string &sServerName,tars::NOTIFYLEVEL level,const std::string &sMessage,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(sServerName, 1);
            _os.write((tars::Int32)level, 2);
            _os.write(sMessage, 3);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"notifyServer", _os.getByteBuffer(), context, _mStatus, callback, true);
        }

        void reportNotifyInfo(const tars::ReportInfo & info,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(info, 1);
            tars::ResponsePacket rep;
            std::map<string, string> _mStatus;
            tars_invoke(tars::TARSNORMAL,"reportNotifyInfo", _os.getByteBuffer(), context, _mStatus, rep);
            if(pResponseContext)
            {
                *pResponseContext = rep.context;
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep.sBuffer);
        }

        void async_reportNotifyInfo(NotifyPrxCallbackPtr callback,const tars::ReportInfo &info,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(info, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"reportNotifyInfo", _os.getByteBuffer(), context, _mStatus, callback);
        }
        
        promise::Future< NotifyPrxCallbackPromise::PromisereportNotifyInfoPtr > promise_async_reportNotifyInfo(const tars::ReportInfo &info,const map<string, string>& context)
        {
            promise::Promise< NotifyPrxCallbackPromise::PromisereportNotifyInfoPtr > promise;
            NotifyPrxCallbackPromisePtr callback = new NotifyPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(info, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"reportNotifyInfo", _os.getByteBuffer(), context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_reportNotifyInfo(NotifyCoroPrxCallbackPtr callback,const tars::ReportInfo &info,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(info, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"reportNotifyInfo", _os.getByteBuffer(), context, _mStatus, callback, true);
        }

        void reportServer(const std::string & sServerName,const std::string & sThreadId,const std::string & sMessage,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(sServerName, 1);
            _os.write(sThreadId, 2);
            _os.write(sMessage, 3);
            tars::ResponsePacket rep;
            std::map<string, string> _mStatus;
            tars_invoke(tars::TARSNORMAL,"reportServer", _os.getByteBuffer(), context, _mStatus, rep);
            if(pResponseContext)
            {
                *pResponseContext = rep.context;
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep.sBuffer);
        }

        void async_reportServer(NotifyPrxCallbackPtr callback,const std::string &sServerName,const std::string &sThreadId,const std::string &sMessage,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(sServerName, 1);
            _os.write(sThreadId, 2);
            _os.write(sMessage, 3);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"reportServer", _os.getByteBuffer(), context, _mStatus, callback);
        }
        
        promise::Future< NotifyPrxCallbackPromise::PromisereportServerPtr > promise_async_reportServer(const std::string &sServerName,const std::string &sThreadId,const std::string &sMessage,const map<string, string>& context)
        {
            promise::Promise< NotifyPrxCallbackPromise::PromisereportServerPtr > promise;
            NotifyPrxCallbackPromisePtr callback = new NotifyPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(sServerName, 1);
            _os.write(sThreadId, 2);
            _os.write(sMessage, 3);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"reportServer", _os.getByteBuffer(), context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_reportServer(NotifyCoroPrxCallbackPtr callback,const std::string &sServerName,const std::string &sThreadId,const std::string &sMessage,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriter> _os;
            _os.write(sServerName, 1);
            _os.write(sThreadId, 2);
            _os.write(sMessage, 3);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"reportServer", _os.getByteBuffer(), context, _mStatus, callback, true);
        }

        NotifyProxy* tars_hash(int64_t key)
        {
            return (NotifyProxy*)ServantProxy::tars_hash(key);
        }

        NotifyProxy* tars_consistent_hash(int64_t key)
        {
            return (NotifyProxy*)ServantProxy::tars_consistent_hash(key);
        }

        NotifyProxy* tars_set_timeout(int msecond)
        {
            return (NotifyProxy*)ServantProxy::tars_set_timeout(msecond);
        }

    };
    typedef tars::TC_AutoPtr<NotifyProxy> NotifyPrx;

    /* servant for server */
    class Notify : public tars::Servant
    {
    public:
        virtual ~Notify(){}
        virtual tars::Int32 getNotifyInfo(const tars::NotifyKey & stKey,tars::NotifyInfo &stInfo,tars::TarsCurrentPtr current) = 0;
        static void async_response_getNotifyInfo(tars::TarsCurrentPtr current, tars::Int32 _ret, const tars::NotifyInfo &stInfo)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());
                tarsAttr.put("", _ret);
                tarsAttr.put("stInfo", stInfo);

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriter> _os;
                _os.write(_ret, 0);

                _os.write(stInfo, 2);

                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual void notifyServer(const std::string & sServerName,tars::NOTIFYLEVEL level,const std::string & sMessage,tars::TarsCurrentPtr current) = 0;
        static void async_response_notifyServer(tars::TarsCurrentPtr current)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriter> _os;
                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual void reportNotifyInfo(const tars::ReportInfo & info,tars::TarsCurrentPtr current) = 0;
        static void async_response_reportNotifyInfo(tars::TarsCurrentPtr current)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriter> _os;
                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

        virtual void reportServer(const std::string & sServerName,const std::string & sThreadId,const std::string & sMessage,tars::TarsCurrentPtr current) = 0;
        static void async_response_reportServer(tars::TarsCurrentPtr current)
        {
            if (current->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                tarsAttr.setVersion(current->getRequestVersion());

                vector<char> sTupResponseBuffer;
                tarsAttr.encode(sTupResponseBuffer);
                current->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriter> _os;
                current->sendResponse(tars::TARSSERVERSUCCESS, _os.getByteBuffer());
            }
        }

    public:
        int onDispatch(tars::TarsCurrentPtr _current, vector<char> &_sResponseBuffer)
        {
            static ::std::string __tars__Notify_all[]=
            {
                "getNotifyInfo",
                "notifyServer",
                "reportNotifyInfo",
                "reportServer"
            };

            pair<string*, string*> r = equal_range(__tars__Notify_all, __tars__Notify_all+4, _current->getFuncName());
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __tars__Notify_all)
            {
                case 0:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    tars::NotifyKey stKey;
                    tars::NotifyInfo stInfo;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("stKey", stKey);
                        tarsAttr.getByDefault("stInfo", stInfo, stInfo);
                    }
                    else
                    {
                        _is.read(stKey, 1, true);
                        _is.read(stInfo, 2, false);
                    }
                    tars::Int32 _ret = getNotifyInfo(stKey,stInfo, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION )
                        {
                            UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.put("", _ret);
                            tarsAttr.put("stInfo", stInfo);
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriter> _os;
                            _os.write(_ret, 0);
                            _os.write(stInfo, 2);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string sServerName;
                    tars::NOTIFYLEVEL level = tars::NOTIFYNORMAL;;
                    std::string sMessage;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("sServerName", sServerName);
                        level = (tars::NOTIFYLEVEL) tarsAttr.get<tars::Int32>("level");
                        tarsAttr.get("sMessage", sMessage);
                    }
                    else
                    {
                        _is.read(sServerName, 1, true);
                        tars::Int32 eTemp2 = tars::NOTIFYNORMAL;
                        _is.read(eTemp2, 2, true);
                        level = (tars::NOTIFYLEVEL)eTemp2;
                        _is.read(sMessage, 3, true);
                    }
                    notifyServer(sServerName,level,sMessage, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION )
                        {
                            UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriter> _os;
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    tars::ReportInfo info;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("info", info);
                    }
                    else
                    {
                        _is.read(info, 1, true);
                    }
                    reportNotifyInfo(info, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION )
                        {
                            UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriter> _os;
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string sServerName;
                    std::string sThreadId;
                    std::string sMessage;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                        tarsAttr.setVersion(_current->getRequestVersion());
                        tarsAttr.decode(_current->getRequestBuffer());
                        tarsAttr.get("sServerName", sServerName);
                        tarsAttr.get("sThreadId", sThreadId);
                        tarsAttr.get("sMessage", sMessage);
                    }
                    else
                    {
                        _is.read(sServerName, 1, true);
                        _is.read(sThreadId, 2, true);
                        _is.read(sMessage, 3, true);
                    }
                    reportServer(sServerName,sThreadId,sMessage, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION )
                        {
                            UniAttribute<tars::BufferWriter, tars::BufferReader>  tarsAttr;
                            tarsAttr.setVersion(_current->getRequestVersion());
                            tarsAttr.encode(_sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriter> _os;
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }
    };


}



#endif
